### ISSUE TITLE
ReadOnlyCollectionBase is missing

### ISSUE THREAD

**Issue by kirsan31** [dotnet/source-indexer#59] opened 2020-07-24 11:56 UTC
`ReadOnlyCollectionBase` is missing. For example: https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/FormCollection.cs,31d88d427ce374ce
In .Net framework indexer: https://referencesource.microsoft.com/#mscorlib/system/collections/readonlycollectionbase.cs,8a1b95dcb893d31f

**Comment by alexperovich** [comment] 2020-07-24 20:04
closing as dupe of #60.

**Closed by alexperovich** 2020-07-24 20:04 UTC
